//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resonance.Insight3.Web.Views.Reporting.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewReport_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewReport_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resonance.Insight3.Web.Views.Reporting.App_LocalResources.ViewReport.cshtml", typeof(ViewReport_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Recommendation Boxes.
        /// </summary>
        public static string allrecommendationboxes {
            get {
                return ResourceManager.GetString("allrecommendationboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Schemes.
        /// </summary>
        public static string allschemes {
            get {
                return ResourceManager.GetString("allschemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Segments.
        /// </summary>
        public static string allsegments {
            get {
                return ResourceManager.GetString("allsegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Active Recommendation Strategies.
        /// </summary>
        public static string showallactiverecommendationstrategies {
            get {
                return ResourceManager.GetString("showallactiverecommendationstrategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All But Deleted Recommendation Strategies.
        /// </summary>
        public static string showallbutdeletedrecommendation {
            get {
                return ResourceManager.GetString("showallbutdeletedrecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Recommendation Strategies.
        /// </summary>
        public static string showallrecommendationstrategies {
            get {
                return ResourceManager.GetString("showallrecommendationstrategies", resourceCulture);
            }
        }
    }
}
