//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resonance.Insight3.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resonance.Insight3.Web.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Explorer.
        /// </summary>
        public static string AccountExplorerText {
            get {
                return ResourceManager.GetString("AccountExplorerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is required..
        /// </summary>
        public static string AccountRequiredText {
            get {
                return ResourceManager.GetString("AccountRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Explorer.
        /// </summary>
        public static string AssetExplorerText {
            get {
                return ResourceManager.GetString("AssetExplorerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * indicates a required field.
        /// </summary>
        public static string AsterikRequired {
            get {
                return ResourceManager.GetString("AsterikRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string ClickHereText {
            get {
                return ResourceManager.GetString("ClickHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string CollapseallText {
            get {
                return ResourceManager.GetString("CollapseallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display items with the following statuses:.
        /// </summary>
        public static string DisplayStatusText {
            get {
                return ResourceManager.GetString("DisplayStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        public static string ExpandallText {
            get {
                return ResourceManager.GetString("ExpandallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to keep working..
        /// </summary>
        public static string KeepWorkingText {
            get {
                return ResourceManager.GetString("KeepWorkingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as:.
        /// </summary>
        public static string LoggedInText {
            get {
                return ResourceManager.GetString("LoggedInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account with this username and password can be found..
        /// </summary>
        public static string LoginAccountDoesNotExist {
            get {
                return ResourceManager.GetString("LoginAccountDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN AGAIN.
        /// </summary>
        public static string LoginAgainText {
            get {
                return ResourceManager.GetString("LoginAgainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded your login attempts, and your account has been locked for 15 minutes.  Please try again shortly..
        /// </summary>
        public static string LoginAttemptsExceeded {
            get {
                return ResourceManager.GetString("LoginAttemptsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered is invalid.  Please try again..
        /// </summary>
        public static string LoginInvalidCredentials {
            get {
                return ResourceManager.GetString("LoginInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.  This account will be locked after {0} unsuccessful attempts..
        /// </summary>
        public static string LoginInvalidCredentialsWithCount {
            get {
                return ResourceManager.GetString("LoginInvalidCredentialsWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have logged out successfully..
        /// </summary>
        public static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequiredText {
            get {
                return ResourceManager.GetString("PasswordRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been a problem loading this panel..
        /// </summary>
        public static string ReloadText {
            get {
                return ResourceManager.GetString("ReloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsText {
            get {
                return ResourceManager.GetString("ReportsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save is enabled after required fields are completed or modified..
        /// </summary>
        public static string SaveButtonDisabled {
            get {
                return ResourceManager.GetString("SaveButtonDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired after 30 minutes of inactivity.  Please sign on again..
        /// </summary>
        public static string SessionExpiredText {
            get {
                return ResourceManager.GetString("SessionExpiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session timeout.
        /// </summary>
        public static string SessionTimeoutText {
            get {
                return ResourceManager.GetString("SessionTimeoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session will expire in:.
        /// </summary>
        public static string SessionWarningTex {
            get {
                return ResourceManager.GetString("SessionWarningTex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string StatusActiveText {
            get {
                return ResourceManager.GetString("StatusActiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string StatusDeletedText {
            get {
                return ResourceManager.GetString("StatusDeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string StatusInactiveText {
            get {
                return ResourceManager.GetString("StatusInactiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string StatusPendingText {
            get {
                return ResourceManager.GetString("StatusPendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsText {
            get {
                return ResourceManager.GetString("ToolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to try and reload..
        /// </summary>
        public static string ToReloadText {
            get {
                return ResourceManager.GetString("ToReloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is required..
        /// </summary>
        public static string UserIDRequiredText {
            get {
                return ResourceManager.GetString("UserIDRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string UserSettingsText {
            get {
                return ResourceManager.GetString("UserSettingsText", resourceCulture);
            }
        }
    }
}
